import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Navbar from "@/components/Navbar";

const noto = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={(noto.className, "p-3")}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					themes={["light", "dark", "system"]}
					enableSystem
					disableTransitionOnChange
				>
					<main className="max-w-2xl space-y-20 mx-auto py-24 pt-12 px-1">
						{children}
					</main>
					<Navbar />
				</ThemeProvider>
			</body>
		</html>
	);
}
